// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufCustomType.proto

#ifndef PROTOBUF_ProtobufCustomType_2eproto__INCLUDED
#define PROTOBUF_ProtobufCustomType_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_ProtobufCustomType_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[8];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsOctetImpl();
void InitDefaultsOctet();
void InitDefaultsLongSeqTestImpl();
void InitDefaultsLongSeqTest();
void InitDefaultsDoubleSeqTestImpl();
void InitDefaultsDoubleSeqTest();
void InitDefaultsStringTestImpl();
void InitDefaultsStringTest();
void InitDefaultsStringSeqTestImpl();
void InitDefaultsStringSeqTest();
void InitDefaultsArrayLongSeqTestImpl();
void InitDefaultsArrayLongSeqTest();
void InitDefaultsSeqArrayLongSeqTestImpl();
void InitDefaultsSeqArrayLongSeqTest();
void InitDefaultsTestCustomTypeImpl();
void InitDefaultsTestCustomType();
inline void InitDefaults() {
  InitDefaultsOctet();
  InitDefaultsLongSeqTest();
  InitDefaultsDoubleSeqTest();
  InitDefaultsStringTest();
  InitDefaultsStringSeqTest();
  InitDefaultsArrayLongSeqTest();
  InitDefaultsSeqArrayLongSeqTest();
  InitDefaultsTestCustomType();
}
}  // namespace protobuf_ProtobufCustomType_2eproto
namespace myprotobuf {
class ArrayLongSeqTest;
class ArrayLongSeqTestDefaultTypeInternal;
extern ArrayLongSeqTestDefaultTypeInternal _ArrayLongSeqTest_default_instance_;
class DoubleSeqTest;
class DoubleSeqTestDefaultTypeInternal;
extern DoubleSeqTestDefaultTypeInternal _DoubleSeqTest_default_instance_;
class LongSeqTest;
class LongSeqTestDefaultTypeInternal;
extern LongSeqTestDefaultTypeInternal _LongSeqTest_default_instance_;
class Octet;
class OctetDefaultTypeInternal;
extern OctetDefaultTypeInternal _Octet_default_instance_;
class SeqArrayLongSeqTest;
class SeqArrayLongSeqTestDefaultTypeInternal;
extern SeqArrayLongSeqTestDefaultTypeInternal _SeqArrayLongSeqTest_default_instance_;
class StringSeqTest;
class StringSeqTestDefaultTypeInternal;
extern StringSeqTestDefaultTypeInternal _StringSeqTest_default_instance_;
class StringTest;
class StringTestDefaultTypeInternal;
extern StringTestDefaultTypeInternal _StringTest_default_instance_;
class TestCustomType;
class TestCustomTypeDefaultTypeInternal;
extern TestCustomTypeDefaultTypeInternal _TestCustomType_default_instance_;
}  // namespace myprotobuf
namespace myprotobuf {

// ===================================================================

class Octet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:myprotobuf.Octet) */ {
 public:
  Octet();
  virtual ~Octet();

  Octet(const Octet& from);

  inline Octet& operator=(const Octet& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Octet(Octet&& from) noexcept
    : Octet() {
    *this = ::std::move(from);
  }

  inline Octet& operator=(Octet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Octet& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Octet* internal_default_instance() {
    return reinterpret_cast<const Octet*>(
               &_Octet_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Octet* other);
  friend void swap(Octet& a, Octet& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Octet* New() const PROTOBUF_FINAL { return New(NULL); }

  Octet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Octet& from);
  void MergeFrom(const Octet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Octet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes octet = 1;
  void clear_octet();
  static const int kOctetFieldNumber = 1;
  const ::std::string& octet() const;
  void set_octet(const ::std::string& value);
  #if LANG_CXX11
  void set_octet(::std::string&& value);
  #endif
  void set_octet(const char* value);
  void set_octet(const void* value, size_t size);
  ::std::string* mutable_octet();
  ::std::string* release_octet();
  void set_allocated_octet(::std::string* octet);

  // @@protoc_insertion_point(class_scope:myprotobuf.Octet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr octet_;
  mutable int _cached_size_;
  friend struct ::protobuf_ProtobufCustomType_2eproto::TableStruct;
  friend void ::protobuf_ProtobufCustomType_2eproto::InitDefaultsOctetImpl();
};
// -------------------------------------------------------------------

class LongSeqTest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:myprotobuf.LongSeqTest) */ {
 public:
  LongSeqTest();
  virtual ~LongSeqTest();

  LongSeqTest(const LongSeqTest& from);

  inline LongSeqTest& operator=(const LongSeqTest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LongSeqTest(LongSeqTest&& from) noexcept
    : LongSeqTest() {
    *this = ::std::move(from);
  }

  inline LongSeqTest& operator=(LongSeqTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LongSeqTest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LongSeqTest* internal_default_instance() {
    return reinterpret_cast<const LongSeqTest*>(
               &_LongSeqTest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(LongSeqTest* other);
  friend void swap(LongSeqTest& a, LongSeqTest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LongSeqTest* New() const PROTOBUF_FINAL { return New(NULL); }

  LongSeqTest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LongSeqTest& from);
  void MergeFrom(const LongSeqTest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LongSeqTest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated sfixed32 long_mem = 1;
  int long_mem_size() const;
  void clear_long_mem();
  static const int kLongMemFieldNumber = 1;
  ::google::protobuf::int32 long_mem(int index) const;
  void set_long_mem(int index, ::google::protobuf::int32 value);
  void add_long_mem(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      long_mem() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_long_mem();

  // @@protoc_insertion_point(class_scope:myprotobuf.LongSeqTest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > long_mem_;
  mutable int _long_mem_cached_byte_size_;
  mutable int _cached_size_;
  friend struct ::protobuf_ProtobufCustomType_2eproto::TableStruct;
  friend void ::protobuf_ProtobufCustomType_2eproto::InitDefaultsLongSeqTestImpl();
};
// -------------------------------------------------------------------

class DoubleSeqTest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:myprotobuf.DoubleSeqTest) */ {
 public:
  DoubleSeqTest();
  virtual ~DoubleSeqTest();

  DoubleSeqTest(const DoubleSeqTest& from);

  inline DoubleSeqTest& operator=(const DoubleSeqTest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DoubleSeqTest(DoubleSeqTest&& from) noexcept
    : DoubleSeqTest() {
    *this = ::std::move(from);
  }

  inline DoubleSeqTest& operator=(DoubleSeqTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DoubleSeqTest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DoubleSeqTest* internal_default_instance() {
    return reinterpret_cast<const DoubleSeqTest*>(
               &_DoubleSeqTest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(DoubleSeqTest* other);
  friend void swap(DoubleSeqTest& a, DoubleSeqTest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DoubleSeqTest* New() const PROTOBUF_FINAL { return New(NULL); }

  DoubleSeqTest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DoubleSeqTest& from);
  void MergeFrom(const DoubleSeqTest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DoubleSeqTest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double double_mem = 1;
  int double_mem_size() const;
  void clear_double_mem();
  static const int kDoubleMemFieldNumber = 1;
  double double_mem(int index) const;
  void set_double_mem(int index, double value);
  void add_double_mem(double value);
  const ::google::protobuf::RepeatedField< double >&
      double_mem() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_double_mem();

  // @@protoc_insertion_point(class_scope:myprotobuf.DoubleSeqTest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< double > double_mem_;
  mutable int _double_mem_cached_byte_size_;
  mutable int _cached_size_;
  friend struct ::protobuf_ProtobufCustomType_2eproto::TableStruct;
  friend void ::protobuf_ProtobufCustomType_2eproto::InitDefaultsDoubleSeqTestImpl();
};
// -------------------------------------------------------------------

class StringTest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:myprotobuf.StringTest) */ {
 public:
  StringTest();
  virtual ~StringTest();

  StringTest(const StringTest& from);

  inline StringTest& operator=(const StringTest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StringTest(StringTest&& from) noexcept
    : StringTest() {
    *this = ::std::move(from);
  }

  inline StringTest& operator=(StringTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StringTest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StringTest* internal_default_instance() {
    return reinterpret_cast<const StringTest*>(
               &_StringTest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(StringTest* other);
  friend void swap(StringTest& a, StringTest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StringTest* New() const PROTOBUF_FINAL { return New(NULL); }

  StringTest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StringTest& from);
  void MergeFrom(const StringTest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StringTest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes char_mem = 1;
  int char_mem_size() const;
  void clear_char_mem();
  static const int kCharMemFieldNumber = 1;
  const ::std::string& char_mem(int index) const;
  ::std::string* mutable_char_mem(int index);
  void set_char_mem(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_char_mem(int index, ::std::string&& value);
  #endif
  void set_char_mem(int index, const char* value);
  void set_char_mem(int index, const void* value, size_t size);
  ::std::string* add_char_mem();
  void add_char_mem(const ::std::string& value);
  #if LANG_CXX11
  void add_char_mem(::std::string&& value);
  #endif
  void add_char_mem(const char* value);
  void add_char_mem(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& char_mem() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_char_mem();

  // @@protoc_insertion_point(class_scope:myprotobuf.StringTest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> char_mem_;
  mutable int _cached_size_;
  friend struct ::protobuf_ProtobufCustomType_2eproto::TableStruct;
  friend void ::protobuf_ProtobufCustomType_2eproto::InitDefaultsStringTestImpl();
};
// -------------------------------------------------------------------

class StringSeqTest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:myprotobuf.StringSeqTest) */ {
 public:
  StringSeqTest();
  virtual ~StringSeqTest();

  StringSeqTest(const StringSeqTest& from);

  inline StringSeqTest& operator=(const StringSeqTest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StringSeqTest(StringSeqTest&& from) noexcept
    : StringSeqTest() {
    *this = ::std::move(from);
  }

  inline StringSeqTest& operator=(StringSeqTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StringSeqTest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StringSeqTest* internal_default_instance() {
    return reinterpret_cast<const StringSeqTest*>(
               &_StringSeqTest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(StringSeqTest* other);
  friend void swap(StringSeqTest& a, StringSeqTest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StringSeqTest* New() const PROTOBUF_FINAL { return New(NULL); }

  StringSeqTest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StringSeqTest& from);
  void MergeFrom(const StringSeqTest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StringSeqTest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .myprotobuf.StringTest string_mem = 1;
  int string_mem_size() const;
  void clear_string_mem();
  static const int kStringMemFieldNumber = 1;
  const ::myprotobuf::StringTest& string_mem(int index) const;
  ::myprotobuf::StringTest* mutable_string_mem(int index);
  ::myprotobuf::StringTest* add_string_mem();
  ::google::protobuf::RepeatedPtrField< ::myprotobuf::StringTest >*
      mutable_string_mem();
  const ::google::protobuf::RepeatedPtrField< ::myprotobuf::StringTest >&
      string_mem() const;

  // @@protoc_insertion_point(class_scope:myprotobuf.StringSeqTest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::myprotobuf::StringTest > string_mem_;
  mutable int _cached_size_;
  friend struct ::protobuf_ProtobufCustomType_2eproto::TableStruct;
  friend void ::protobuf_ProtobufCustomType_2eproto::InitDefaultsStringSeqTestImpl();
};
// -------------------------------------------------------------------

class ArrayLongSeqTest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:myprotobuf.ArrayLongSeqTest) */ {
 public:
  ArrayLongSeqTest();
  virtual ~ArrayLongSeqTest();

  ArrayLongSeqTest(const ArrayLongSeqTest& from);

  inline ArrayLongSeqTest& operator=(const ArrayLongSeqTest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArrayLongSeqTest(ArrayLongSeqTest&& from) noexcept
    : ArrayLongSeqTest() {
    *this = ::std::move(from);
  }

  inline ArrayLongSeqTest& operator=(ArrayLongSeqTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ArrayLongSeqTest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArrayLongSeqTest* internal_default_instance() {
    return reinterpret_cast<const ArrayLongSeqTest*>(
               &_ArrayLongSeqTest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ArrayLongSeqTest* other);
  friend void swap(ArrayLongSeqTest& a, ArrayLongSeqTest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArrayLongSeqTest* New() const PROTOBUF_FINAL { return New(NULL); }

  ArrayLongSeqTest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ArrayLongSeqTest& from);
  void MergeFrom(const ArrayLongSeqTest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ArrayLongSeqTest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .myprotobuf.LongSeqTest array_long_seq_mem = 1;
  int array_long_seq_mem_size() const;
  void clear_array_long_seq_mem();
  static const int kArrayLongSeqMemFieldNumber = 1;
  const ::myprotobuf::LongSeqTest& array_long_seq_mem(int index) const;
  ::myprotobuf::LongSeqTest* mutable_array_long_seq_mem(int index);
  ::myprotobuf::LongSeqTest* add_array_long_seq_mem();
  ::google::protobuf::RepeatedPtrField< ::myprotobuf::LongSeqTest >*
      mutable_array_long_seq_mem();
  const ::google::protobuf::RepeatedPtrField< ::myprotobuf::LongSeqTest >&
      array_long_seq_mem() const;

  // @@protoc_insertion_point(class_scope:myprotobuf.ArrayLongSeqTest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::myprotobuf::LongSeqTest > array_long_seq_mem_;
  mutable int _cached_size_;
  friend struct ::protobuf_ProtobufCustomType_2eproto::TableStruct;
  friend void ::protobuf_ProtobufCustomType_2eproto::InitDefaultsArrayLongSeqTestImpl();
};
// -------------------------------------------------------------------

class SeqArrayLongSeqTest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:myprotobuf.SeqArrayLongSeqTest) */ {
 public:
  SeqArrayLongSeqTest();
  virtual ~SeqArrayLongSeqTest();

  SeqArrayLongSeqTest(const SeqArrayLongSeqTest& from);

  inline SeqArrayLongSeqTest& operator=(const SeqArrayLongSeqTest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SeqArrayLongSeqTest(SeqArrayLongSeqTest&& from) noexcept
    : SeqArrayLongSeqTest() {
    *this = ::std::move(from);
  }

  inline SeqArrayLongSeqTest& operator=(SeqArrayLongSeqTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SeqArrayLongSeqTest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SeqArrayLongSeqTest* internal_default_instance() {
    return reinterpret_cast<const SeqArrayLongSeqTest*>(
               &_SeqArrayLongSeqTest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(SeqArrayLongSeqTest* other);
  friend void swap(SeqArrayLongSeqTest& a, SeqArrayLongSeqTest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SeqArrayLongSeqTest* New() const PROTOBUF_FINAL { return New(NULL); }

  SeqArrayLongSeqTest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SeqArrayLongSeqTest& from);
  void MergeFrom(const SeqArrayLongSeqTest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SeqArrayLongSeqTest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .myprotobuf.ArrayLongSeqTest seq_array_long_seq_mem = 1;
  int seq_array_long_seq_mem_size() const;
  void clear_seq_array_long_seq_mem();
  static const int kSeqArrayLongSeqMemFieldNumber = 1;
  const ::myprotobuf::ArrayLongSeqTest& seq_array_long_seq_mem(int index) const;
  ::myprotobuf::ArrayLongSeqTest* mutable_seq_array_long_seq_mem(int index);
  ::myprotobuf::ArrayLongSeqTest* add_seq_array_long_seq_mem();
  ::google::protobuf::RepeatedPtrField< ::myprotobuf::ArrayLongSeqTest >*
      mutable_seq_array_long_seq_mem();
  const ::google::protobuf::RepeatedPtrField< ::myprotobuf::ArrayLongSeqTest >&
      seq_array_long_seq_mem() const;

  // @@protoc_insertion_point(class_scope:myprotobuf.SeqArrayLongSeqTest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::myprotobuf::ArrayLongSeqTest > seq_array_long_seq_mem_;
  mutable int _cached_size_;
  friend struct ::protobuf_ProtobufCustomType_2eproto::TableStruct;
  friend void ::protobuf_ProtobufCustomType_2eproto::InitDefaultsSeqArrayLongSeqTestImpl();
};
// -------------------------------------------------------------------

class TestCustomType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:myprotobuf.TestCustomType) */ {
 public:
  TestCustomType();
  virtual ~TestCustomType();

  TestCustomType(const TestCustomType& from);

  inline TestCustomType& operator=(const TestCustomType& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TestCustomType(TestCustomType&& from) noexcept
    : TestCustomType() {
    *this = ::std::move(from);
  }

  inline TestCustomType& operator=(TestCustomType&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TestCustomType& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TestCustomType* internal_default_instance() {
    return reinterpret_cast<const TestCustomType*>(
               &_TestCustomType_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(TestCustomType* other);
  friend void swap(TestCustomType& a, TestCustomType& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TestCustomType* New() const PROTOBUF_FINAL { return New(NULL); }

  TestCustomType* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TestCustomType& from);
  void MergeFrom(const TestCustomType& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TestCustomType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .myprotobuf.Octet test_octet = 2;
  int test_octet_size() const;
  void clear_test_octet();
  static const int kTestOctetFieldNumber = 2;
  const ::myprotobuf::Octet& test_octet(int index) const;
  ::myprotobuf::Octet* mutable_test_octet(int index);
  ::myprotobuf::Octet* add_test_octet();
  ::google::protobuf::RepeatedPtrField< ::myprotobuf::Octet >*
      mutable_test_octet();
  const ::google::protobuf::RepeatedPtrField< ::myprotobuf::Octet >&
      test_octet() const;

  // .myprotobuf.LongSeqTest test_long_seq = 3;
  bool has_test_long_seq() const;
  void clear_test_long_seq();
  static const int kTestLongSeqFieldNumber = 3;
  const ::myprotobuf::LongSeqTest& test_long_seq() const;
  ::myprotobuf::LongSeqTest* release_test_long_seq();
  ::myprotobuf::LongSeqTest* mutable_test_long_seq();
  void set_allocated_test_long_seq(::myprotobuf::LongSeqTest* test_long_seq);

  // .myprotobuf.StringTest test_string = 4;
  bool has_test_string() const;
  void clear_test_string();
  static const int kTestStringFieldNumber = 4;
  const ::myprotobuf::StringTest& test_string() const;
  ::myprotobuf::StringTest* release_test_string();
  ::myprotobuf::StringTest* mutable_test_string();
  void set_allocated_test_string(::myprotobuf::StringTest* test_string);

  // .myprotobuf.StringSeqTest test_string_seq = 5;
  bool has_test_string_seq() const;
  void clear_test_string_seq();
  static const int kTestStringSeqFieldNumber = 5;
  const ::myprotobuf::StringSeqTest& test_string_seq() const;
  ::myprotobuf::StringSeqTest* release_test_string_seq();
  ::myprotobuf::StringSeqTest* mutable_test_string_seq();
  void set_allocated_test_string_seq(::myprotobuf::StringSeqTest* test_string_seq);

  // .myprotobuf.DoubleSeqTest test_double_seq = 6;
  bool has_test_double_seq() const;
  void clear_test_double_seq();
  static const int kTestDoubleSeqFieldNumber = 6;
  const ::myprotobuf::DoubleSeqTest& test_double_seq() const;
  ::myprotobuf::DoubleSeqTest* release_test_double_seq();
  ::myprotobuf::DoubleSeqTest* mutable_test_double_seq();
  void set_allocated_test_double_seq(::myprotobuf::DoubleSeqTest* test_double_seq);

  // .myprotobuf.ArrayLongSeqTest test_array_long_seq = 7;
  bool has_test_array_long_seq() const;
  void clear_test_array_long_seq();
  static const int kTestArrayLongSeqFieldNumber = 7;
  const ::myprotobuf::ArrayLongSeqTest& test_array_long_seq() const;
  ::myprotobuf::ArrayLongSeqTest* release_test_array_long_seq();
  ::myprotobuf::ArrayLongSeqTest* mutable_test_array_long_seq();
  void set_allocated_test_array_long_seq(::myprotobuf::ArrayLongSeqTest* test_array_long_seq);

  // .myprotobuf.SeqArrayLongSeqTest seq_array_long_seq_test = 8;
  bool has_seq_array_long_seq_test() const;
  void clear_seq_array_long_seq_test();
  static const int kSeqArrayLongSeqTestFieldNumber = 8;
  const ::myprotobuf::SeqArrayLongSeqTest& seq_array_long_seq_test() const;
  ::myprotobuf::SeqArrayLongSeqTest* release_seq_array_long_seq_test();
  ::myprotobuf::SeqArrayLongSeqTest* mutable_seq_array_long_seq_test();
  void set_allocated_seq_array_long_seq_test(::myprotobuf::SeqArrayLongSeqTest* seq_array_long_seq_test);

  // int32 test_long = 1;
  void clear_test_long();
  static const int kTestLongFieldNumber = 1;
  ::google::protobuf::int32 test_long() const;
  void set_test_long(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:myprotobuf.TestCustomType)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::myprotobuf::Octet > test_octet_;
  ::myprotobuf::LongSeqTest* test_long_seq_;
  ::myprotobuf::StringTest* test_string_;
  ::myprotobuf::StringSeqTest* test_string_seq_;
  ::myprotobuf::DoubleSeqTest* test_double_seq_;
  ::myprotobuf::ArrayLongSeqTest* test_array_long_seq_;
  ::myprotobuf::SeqArrayLongSeqTest* seq_array_long_seq_test_;
  ::google::protobuf::int32 test_long_;
  mutable int _cached_size_;
  friend struct ::protobuf_ProtobufCustomType_2eproto::TableStruct;
  friend void ::protobuf_ProtobufCustomType_2eproto::InitDefaultsTestCustomTypeImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Octet

// bytes octet = 1;
inline void Octet::clear_octet() {
  octet_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Octet::octet() const {
  // @@protoc_insertion_point(field_get:myprotobuf.Octet.octet)
  return octet_.GetNoArena();
}
inline void Octet::set_octet(const ::std::string& value) {
  
  octet_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:myprotobuf.Octet.octet)
}
#if LANG_CXX11
inline void Octet::set_octet(::std::string&& value) {
  
  octet_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:myprotobuf.Octet.octet)
}
#endif
inline void Octet::set_octet(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  octet_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:myprotobuf.Octet.octet)
}
inline void Octet::set_octet(const void* value, size_t size) {
  
  octet_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:myprotobuf.Octet.octet)
}
inline ::std::string* Octet::mutable_octet() {
  
  // @@protoc_insertion_point(field_mutable:myprotobuf.Octet.octet)
  return octet_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Octet::release_octet() {
  // @@protoc_insertion_point(field_release:myprotobuf.Octet.octet)
  
  return octet_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Octet::set_allocated_octet(::std::string* octet) {
  if (octet != NULL) {
    
  } else {
    
  }
  octet_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), octet);
  // @@protoc_insertion_point(field_set_allocated:myprotobuf.Octet.octet)
}

// -------------------------------------------------------------------

// LongSeqTest

// repeated sfixed32 long_mem = 1;
inline int LongSeqTest::long_mem_size() const {
  return long_mem_.size();
}
inline void LongSeqTest::clear_long_mem() {
  long_mem_.Clear();
}
inline ::google::protobuf::int32 LongSeqTest::long_mem(int index) const {
  // @@protoc_insertion_point(field_get:myprotobuf.LongSeqTest.long_mem)
  return long_mem_.Get(index);
}
inline void LongSeqTest::set_long_mem(int index, ::google::protobuf::int32 value) {
  long_mem_.Set(index, value);
  // @@protoc_insertion_point(field_set:myprotobuf.LongSeqTest.long_mem)
}
inline void LongSeqTest::add_long_mem(::google::protobuf::int32 value) {
  long_mem_.Add(value);
  // @@protoc_insertion_point(field_add:myprotobuf.LongSeqTest.long_mem)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
LongSeqTest::long_mem() const {
  // @@protoc_insertion_point(field_list:myprotobuf.LongSeqTest.long_mem)
  return long_mem_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
LongSeqTest::mutable_long_mem() {
  // @@protoc_insertion_point(field_mutable_list:myprotobuf.LongSeqTest.long_mem)
  return &long_mem_;
}

// -------------------------------------------------------------------

// DoubleSeqTest

// repeated double double_mem = 1;
inline int DoubleSeqTest::double_mem_size() const {
  return double_mem_.size();
}
inline void DoubleSeqTest::clear_double_mem() {
  double_mem_.Clear();
}
inline double DoubleSeqTest::double_mem(int index) const {
  // @@protoc_insertion_point(field_get:myprotobuf.DoubleSeqTest.double_mem)
  return double_mem_.Get(index);
}
inline void DoubleSeqTest::set_double_mem(int index, double value) {
  double_mem_.Set(index, value);
  // @@protoc_insertion_point(field_set:myprotobuf.DoubleSeqTest.double_mem)
}
inline void DoubleSeqTest::add_double_mem(double value) {
  double_mem_.Add(value);
  // @@protoc_insertion_point(field_add:myprotobuf.DoubleSeqTest.double_mem)
}
inline const ::google::protobuf::RepeatedField< double >&
DoubleSeqTest::double_mem() const {
  // @@protoc_insertion_point(field_list:myprotobuf.DoubleSeqTest.double_mem)
  return double_mem_;
}
inline ::google::protobuf::RepeatedField< double >*
DoubleSeqTest::mutable_double_mem() {
  // @@protoc_insertion_point(field_mutable_list:myprotobuf.DoubleSeqTest.double_mem)
  return &double_mem_;
}

// -------------------------------------------------------------------

// StringTest

// repeated bytes char_mem = 1;
inline int StringTest::char_mem_size() const {
  return char_mem_.size();
}
inline void StringTest::clear_char_mem() {
  char_mem_.Clear();
}
inline const ::std::string& StringTest::char_mem(int index) const {
  // @@protoc_insertion_point(field_get:myprotobuf.StringTest.char_mem)
  return char_mem_.Get(index);
}
inline ::std::string* StringTest::mutable_char_mem(int index) {
  // @@protoc_insertion_point(field_mutable:myprotobuf.StringTest.char_mem)
  return char_mem_.Mutable(index);
}
inline void StringTest::set_char_mem(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:myprotobuf.StringTest.char_mem)
  char_mem_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void StringTest::set_char_mem(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:myprotobuf.StringTest.char_mem)
  char_mem_.Mutable(index)->assign(std::move(value));
}
#endif
inline void StringTest::set_char_mem(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  char_mem_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:myprotobuf.StringTest.char_mem)
}
inline void StringTest::set_char_mem(int index, const void* value, size_t size) {
  char_mem_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:myprotobuf.StringTest.char_mem)
}
inline ::std::string* StringTest::add_char_mem() {
  // @@protoc_insertion_point(field_add_mutable:myprotobuf.StringTest.char_mem)
  return char_mem_.Add();
}
inline void StringTest::add_char_mem(const ::std::string& value) {
  char_mem_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:myprotobuf.StringTest.char_mem)
}
#if LANG_CXX11
inline void StringTest::add_char_mem(::std::string&& value) {
  char_mem_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:myprotobuf.StringTest.char_mem)
}
#endif
inline void StringTest::add_char_mem(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  char_mem_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:myprotobuf.StringTest.char_mem)
}
inline void StringTest::add_char_mem(const void* value, size_t size) {
  char_mem_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:myprotobuf.StringTest.char_mem)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
StringTest::char_mem() const {
  // @@protoc_insertion_point(field_list:myprotobuf.StringTest.char_mem)
  return char_mem_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
StringTest::mutable_char_mem() {
  // @@protoc_insertion_point(field_mutable_list:myprotobuf.StringTest.char_mem)
  return &char_mem_;
}

// -------------------------------------------------------------------

// StringSeqTest

// repeated .myprotobuf.StringTest string_mem = 1;
inline int StringSeqTest::string_mem_size() const {
  return string_mem_.size();
}
inline void StringSeqTest::clear_string_mem() {
  string_mem_.Clear();
}
inline const ::myprotobuf::StringTest& StringSeqTest::string_mem(int index) const {
  // @@protoc_insertion_point(field_get:myprotobuf.StringSeqTest.string_mem)
  return string_mem_.Get(index);
}
inline ::myprotobuf::StringTest* StringSeqTest::mutable_string_mem(int index) {
  // @@protoc_insertion_point(field_mutable:myprotobuf.StringSeqTest.string_mem)
  return string_mem_.Mutable(index);
}
inline ::myprotobuf::StringTest* StringSeqTest::add_string_mem() {
  // @@protoc_insertion_point(field_add:myprotobuf.StringSeqTest.string_mem)
  return string_mem_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::myprotobuf::StringTest >*
StringSeqTest::mutable_string_mem() {
  // @@protoc_insertion_point(field_mutable_list:myprotobuf.StringSeqTest.string_mem)
  return &string_mem_;
}
inline const ::google::protobuf::RepeatedPtrField< ::myprotobuf::StringTest >&
StringSeqTest::string_mem() const {
  // @@protoc_insertion_point(field_list:myprotobuf.StringSeqTest.string_mem)
  return string_mem_;
}

// -------------------------------------------------------------------

// ArrayLongSeqTest

// repeated .myprotobuf.LongSeqTest array_long_seq_mem = 1;
inline int ArrayLongSeqTest::array_long_seq_mem_size() const {
  return array_long_seq_mem_.size();
}
inline void ArrayLongSeqTest::clear_array_long_seq_mem() {
  array_long_seq_mem_.Clear();
}
inline const ::myprotobuf::LongSeqTest& ArrayLongSeqTest::array_long_seq_mem(int index) const {
  // @@protoc_insertion_point(field_get:myprotobuf.ArrayLongSeqTest.array_long_seq_mem)
  return array_long_seq_mem_.Get(index);
}
inline ::myprotobuf::LongSeqTest* ArrayLongSeqTest::mutable_array_long_seq_mem(int index) {
  // @@protoc_insertion_point(field_mutable:myprotobuf.ArrayLongSeqTest.array_long_seq_mem)
  return array_long_seq_mem_.Mutable(index);
}
inline ::myprotobuf::LongSeqTest* ArrayLongSeqTest::add_array_long_seq_mem() {
  // @@protoc_insertion_point(field_add:myprotobuf.ArrayLongSeqTest.array_long_seq_mem)
  return array_long_seq_mem_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::myprotobuf::LongSeqTest >*
ArrayLongSeqTest::mutable_array_long_seq_mem() {
  // @@protoc_insertion_point(field_mutable_list:myprotobuf.ArrayLongSeqTest.array_long_seq_mem)
  return &array_long_seq_mem_;
}
inline const ::google::protobuf::RepeatedPtrField< ::myprotobuf::LongSeqTest >&
ArrayLongSeqTest::array_long_seq_mem() const {
  // @@protoc_insertion_point(field_list:myprotobuf.ArrayLongSeqTest.array_long_seq_mem)
  return array_long_seq_mem_;
}

// -------------------------------------------------------------------

// SeqArrayLongSeqTest

// repeated .myprotobuf.ArrayLongSeqTest seq_array_long_seq_mem = 1;
inline int SeqArrayLongSeqTest::seq_array_long_seq_mem_size() const {
  return seq_array_long_seq_mem_.size();
}
inline void SeqArrayLongSeqTest::clear_seq_array_long_seq_mem() {
  seq_array_long_seq_mem_.Clear();
}
inline const ::myprotobuf::ArrayLongSeqTest& SeqArrayLongSeqTest::seq_array_long_seq_mem(int index) const {
  // @@protoc_insertion_point(field_get:myprotobuf.SeqArrayLongSeqTest.seq_array_long_seq_mem)
  return seq_array_long_seq_mem_.Get(index);
}
inline ::myprotobuf::ArrayLongSeqTest* SeqArrayLongSeqTest::mutable_seq_array_long_seq_mem(int index) {
  // @@protoc_insertion_point(field_mutable:myprotobuf.SeqArrayLongSeqTest.seq_array_long_seq_mem)
  return seq_array_long_seq_mem_.Mutable(index);
}
inline ::myprotobuf::ArrayLongSeqTest* SeqArrayLongSeqTest::add_seq_array_long_seq_mem() {
  // @@protoc_insertion_point(field_add:myprotobuf.SeqArrayLongSeqTest.seq_array_long_seq_mem)
  return seq_array_long_seq_mem_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::myprotobuf::ArrayLongSeqTest >*
SeqArrayLongSeqTest::mutable_seq_array_long_seq_mem() {
  // @@protoc_insertion_point(field_mutable_list:myprotobuf.SeqArrayLongSeqTest.seq_array_long_seq_mem)
  return &seq_array_long_seq_mem_;
}
inline const ::google::protobuf::RepeatedPtrField< ::myprotobuf::ArrayLongSeqTest >&
SeqArrayLongSeqTest::seq_array_long_seq_mem() const {
  // @@protoc_insertion_point(field_list:myprotobuf.SeqArrayLongSeqTest.seq_array_long_seq_mem)
  return seq_array_long_seq_mem_;
}

// -------------------------------------------------------------------

// TestCustomType

// int32 test_long = 1;
inline void TestCustomType::clear_test_long() {
  test_long_ = 0;
}
inline ::google::protobuf::int32 TestCustomType::test_long() const {
  // @@protoc_insertion_point(field_get:myprotobuf.TestCustomType.test_long)
  return test_long_;
}
inline void TestCustomType::set_test_long(::google::protobuf::int32 value) {
  
  test_long_ = value;
  // @@protoc_insertion_point(field_set:myprotobuf.TestCustomType.test_long)
}

// repeated .myprotobuf.Octet test_octet = 2;
inline int TestCustomType::test_octet_size() const {
  return test_octet_.size();
}
inline void TestCustomType::clear_test_octet() {
  test_octet_.Clear();
}
inline const ::myprotobuf::Octet& TestCustomType::test_octet(int index) const {
  // @@protoc_insertion_point(field_get:myprotobuf.TestCustomType.test_octet)
  return test_octet_.Get(index);
}
inline ::myprotobuf::Octet* TestCustomType::mutable_test_octet(int index) {
  // @@protoc_insertion_point(field_mutable:myprotobuf.TestCustomType.test_octet)
  return test_octet_.Mutable(index);
}
inline ::myprotobuf::Octet* TestCustomType::add_test_octet() {
  // @@protoc_insertion_point(field_add:myprotobuf.TestCustomType.test_octet)
  return test_octet_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::myprotobuf::Octet >*
TestCustomType::mutable_test_octet() {
  // @@protoc_insertion_point(field_mutable_list:myprotobuf.TestCustomType.test_octet)
  return &test_octet_;
}
inline const ::google::protobuf::RepeatedPtrField< ::myprotobuf::Octet >&
TestCustomType::test_octet() const {
  // @@protoc_insertion_point(field_list:myprotobuf.TestCustomType.test_octet)
  return test_octet_;
}

// .myprotobuf.LongSeqTest test_long_seq = 3;
inline bool TestCustomType::has_test_long_seq() const {
  return this != internal_default_instance() && test_long_seq_ != NULL;
}
inline void TestCustomType::clear_test_long_seq() {
  if (GetArenaNoVirtual() == NULL && test_long_seq_ != NULL) {
    delete test_long_seq_;
  }
  test_long_seq_ = NULL;
}
inline const ::myprotobuf::LongSeqTest& TestCustomType::test_long_seq() const {
  const ::myprotobuf::LongSeqTest* p = test_long_seq_;
  // @@protoc_insertion_point(field_get:myprotobuf.TestCustomType.test_long_seq)
  return p != NULL ? *p : *reinterpret_cast<const ::myprotobuf::LongSeqTest*>(
      &::myprotobuf::_LongSeqTest_default_instance_);
}
inline ::myprotobuf::LongSeqTest* TestCustomType::release_test_long_seq() {
  // @@protoc_insertion_point(field_release:myprotobuf.TestCustomType.test_long_seq)
  
  ::myprotobuf::LongSeqTest* temp = test_long_seq_;
  test_long_seq_ = NULL;
  return temp;
}
inline ::myprotobuf::LongSeqTest* TestCustomType::mutable_test_long_seq() {
  
  if (test_long_seq_ == NULL) {
    test_long_seq_ = new ::myprotobuf::LongSeqTest;
  }
  // @@protoc_insertion_point(field_mutable:myprotobuf.TestCustomType.test_long_seq)
  return test_long_seq_;
}
inline void TestCustomType::set_allocated_test_long_seq(::myprotobuf::LongSeqTest* test_long_seq) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete test_long_seq_;
  }
  if (test_long_seq) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      test_long_seq = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, test_long_seq, submessage_arena);
    }
    
  } else {
    
  }
  test_long_seq_ = test_long_seq;
  // @@protoc_insertion_point(field_set_allocated:myprotobuf.TestCustomType.test_long_seq)
}

// .myprotobuf.StringTest test_string = 4;
inline bool TestCustomType::has_test_string() const {
  return this != internal_default_instance() && test_string_ != NULL;
}
inline void TestCustomType::clear_test_string() {
  if (GetArenaNoVirtual() == NULL && test_string_ != NULL) {
    delete test_string_;
  }
  test_string_ = NULL;
}
inline const ::myprotobuf::StringTest& TestCustomType::test_string() const {
  const ::myprotobuf::StringTest* p = test_string_;
  // @@protoc_insertion_point(field_get:myprotobuf.TestCustomType.test_string)
  return p != NULL ? *p : *reinterpret_cast<const ::myprotobuf::StringTest*>(
      &::myprotobuf::_StringTest_default_instance_);
}
inline ::myprotobuf::StringTest* TestCustomType::release_test_string() {
  // @@protoc_insertion_point(field_release:myprotobuf.TestCustomType.test_string)
  
  ::myprotobuf::StringTest* temp = test_string_;
  test_string_ = NULL;
  return temp;
}
inline ::myprotobuf::StringTest* TestCustomType::mutable_test_string() {
  
  if (test_string_ == NULL) {
    test_string_ = new ::myprotobuf::StringTest;
  }
  // @@protoc_insertion_point(field_mutable:myprotobuf.TestCustomType.test_string)
  return test_string_;
}
inline void TestCustomType::set_allocated_test_string(::myprotobuf::StringTest* test_string) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete test_string_;
  }
  if (test_string) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      test_string = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, test_string, submessage_arena);
    }
    
  } else {
    
  }
  test_string_ = test_string;
  // @@protoc_insertion_point(field_set_allocated:myprotobuf.TestCustomType.test_string)
}

// .myprotobuf.StringSeqTest test_string_seq = 5;
inline bool TestCustomType::has_test_string_seq() const {
  return this != internal_default_instance() && test_string_seq_ != NULL;
}
inline void TestCustomType::clear_test_string_seq() {
  if (GetArenaNoVirtual() == NULL && test_string_seq_ != NULL) {
    delete test_string_seq_;
  }
  test_string_seq_ = NULL;
}
inline const ::myprotobuf::StringSeqTest& TestCustomType::test_string_seq() const {
  const ::myprotobuf::StringSeqTest* p = test_string_seq_;
  // @@protoc_insertion_point(field_get:myprotobuf.TestCustomType.test_string_seq)
  return p != NULL ? *p : *reinterpret_cast<const ::myprotobuf::StringSeqTest*>(
      &::myprotobuf::_StringSeqTest_default_instance_);
}
inline ::myprotobuf::StringSeqTest* TestCustomType::release_test_string_seq() {
  // @@protoc_insertion_point(field_release:myprotobuf.TestCustomType.test_string_seq)
  
  ::myprotobuf::StringSeqTest* temp = test_string_seq_;
  test_string_seq_ = NULL;
  return temp;
}
inline ::myprotobuf::StringSeqTest* TestCustomType::mutable_test_string_seq() {
  
  if (test_string_seq_ == NULL) {
    test_string_seq_ = new ::myprotobuf::StringSeqTest;
  }
  // @@protoc_insertion_point(field_mutable:myprotobuf.TestCustomType.test_string_seq)
  return test_string_seq_;
}
inline void TestCustomType::set_allocated_test_string_seq(::myprotobuf::StringSeqTest* test_string_seq) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete test_string_seq_;
  }
  if (test_string_seq) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      test_string_seq = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, test_string_seq, submessage_arena);
    }
    
  } else {
    
  }
  test_string_seq_ = test_string_seq;
  // @@protoc_insertion_point(field_set_allocated:myprotobuf.TestCustomType.test_string_seq)
}

// .myprotobuf.DoubleSeqTest test_double_seq = 6;
inline bool TestCustomType::has_test_double_seq() const {
  return this != internal_default_instance() && test_double_seq_ != NULL;
}
inline void TestCustomType::clear_test_double_seq() {
  if (GetArenaNoVirtual() == NULL && test_double_seq_ != NULL) {
    delete test_double_seq_;
  }
  test_double_seq_ = NULL;
}
inline const ::myprotobuf::DoubleSeqTest& TestCustomType::test_double_seq() const {
  const ::myprotobuf::DoubleSeqTest* p = test_double_seq_;
  // @@protoc_insertion_point(field_get:myprotobuf.TestCustomType.test_double_seq)
  return p != NULL ? *p : *reinterpret_cast<const ::myprotobuf::DoubleSeqTest*>(
      &::myprotobuf::_DoubleSeqTest_default_instance_);
}
inline ::myprotobuf::DoubleSeqTest* TestCustomType::release_test_double_seq() {
  // @@protoc_insertion_point(field_release:myprotobuf.TestCustomType.test_double_seq)
  
  ::myprotobuf::DoubleSeqTest* temp = test_double_seq_;
  test_double_seq_ = NULL;
  return temp;
}
inline ::myprotobuf::DoubleSeqTest* TestCustomType::mutable_test_double_seq() {
  
  if (test_double_seq_ == NULL) {
    test_double_seq_ = new ::myprotobuf::DoubleSeqTest;
  }
  // @@protoc_insertion_point(field_mutable:myprotobuf.TestCustomType.test_double_seq)
  return test_double_seq_;
}
inline void TestCustomType::set_allocated_test_double_seq(::myprotobuf::DoubleSeqTest* test_double_seq) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete test_double_seq_;
  }
  if (test_double_seq) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      test_double_seq = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, test_double_seq, submessage_arena);
    }
    
  } else {
    
  }
  test_double_seq_ = test_double_seq;
  // @@protoc_insertion_point(field_set_allocated:myprotobuf.TestCustomType.test_double_seq)
}

// .myprotobuf.ArrayLongSeqTest test_array_long_seq = 7;
inline bool TestCustomType::has_test_array_long_seq() const {
  return this != internal_default_instance() && test_array_long_seq_ != NULL;
}
inline void TestCustomType::clear_test_array_long_seq() {
  if (GetArenaNoVirtual() == NULL && test_array_long_seq_ != NULL) {
    delete test_array_long_seq_;
  }
  test_array_long_seq_ = NULL;
}
inline const ::myprotobuf::ArrayLongSeqTest& TestCustomType::test_array_long_seq() const {
  const ::myprotobuf::ArrayLongSeqTest* p = test_array_long_seq_;
  // @@protoc_insertion_point(field_get:myprotobuf.TestCustomType.test_array_long_seq)
  return p != NULL ? *p : *reinterpret_cast<const ::myprotobuf::ArrayLongSeqTest*>(
      &::myprotobuf::_ArrayLongSeqTest_default_instance_);
}
inline ::myprotobuf::ArrayLongSeqTest* TestCustomType::release_test_array_long_seq() {
  // @@protoc_insertion_point(field_release:myprotobuf.TestCustomType.test_array_long_seq)
  
  ::myprotobuf::ArrayLongSeqTest* temp = test_array_long_seq_;
  test_array_long_seq_ = NULL;
  return temp;
}
inline ::myprotobuf::ArrayLongSeqTest* TestCustomType::mutable_test_array_long_seq() {
  
  if (test_array_long_seq_ == NULL) {
    test_array_long_seq_ = new ::myprotobuf::ArrayLongSeqTest;
  }
  // @@protoc_insertion_point(field_mutable:myprotobuf.TestCustomType.test_array_long_seq)
  return test_array_long_seq_;
}
inline void TestCustomType::set_allocated_test_array_long_seq(::myprotobuf::ArrayLongSeqTest* test_array_long_seq) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete test_array_long_seq_;
  }
  if (test_array_long_seq) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      test_array_long_seq = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, test_array_long_seq, submessage_arena);
    }
    
  } else {
    
  }
  test_array_long_seq_ = test_array_long_seq;
  // @@protoc_insertion_point(field_set_allocated:myprotobuf.TestCustomType.test_array_long_seq)
}

// .myprotobuf.SeqArrayLongSeqTest seq_array_long_seq_test = 8;
inline bool TestCustomType::has_seq_array_long_seq_test() const {
  return this != internal_default_instance() && seq_array_long_seq_test_ != NULL;
}
inline void TestCustomType::clear_seq_array_long_seq_test() {
  if (GetArenaNoVirtual() == NULL && seq_array_long_seq_test_ != NULL) {
    delete seq_array_long_seq_test_;
  }
  seq_array_long_seq_test_ = NULL;
}
inline const ::myprotobuf::SeqArrayLongSeqTest& TestCustomType::seq_array_long_seq_test() const {
  const ::myprotobuf::SeqArrayLongSeqTest* p = seq_array_long_seq_test_;
  // @@protoc_insertion_point(field_get:myprotobuf.TestCustomType.seq_array_long_seq_test)
  return p != NULL ? *p : *reinterpret_cast<const ::myprotobuf::SeqArrayLongSeqTest*>(
      &::myprotobuf::_SeqArrayLongSeqTest_default_instance_);
}
inline ::myprotobuf::SeqArrayLongSeqTest* TestCustomType::release_seq_array_long_seq_test() {
  // @@protoc_insertion_point(field_release:myprotobuf.TestCustomType.seq_array_long_seq_test)
  
  ::myprotobuf::SeqArrayLongSeqTest* temp = seq_array_long_seq_test_;
  seq_array_long_seq_test_ = NULL;
  return temp;
}
inline ::myprotobuf::SeqArrayLongSeqTest* TestCustomType::mutable_seq_array_long_seq_test() {
  
  if (seq_array_long_seq_test_ == NULL) {
    seq_array_long_seq_test_ = new ::myprotobuf::SeqArrayLongSeqTest;
  }
  // @@protoc_insertion_point(field_mutable:myprotobuf.TestCustomType.seq_array_long_seq_test)
  return seq_array_long_seq_test_;
}
inline void TestCustomType::set_allocated_seq_array_long_seq_test(::myprotobuf::SeqArrayLongSeqTest* seq_array_long_seq_test) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete seq_array_long_seq_test_;
  }
  if (seq_array_long_seq_test) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      seq_array_long_seq_test = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, seq_array_long_seq_test, submessage_arena);
    }
    
  } else {
    
  }
  seq_array_long_seq_test_ = seq_array_long_seq_test;
  // @@protoc_insertion_point(field_set_allocated:myprotobuf.TestCustomType.seq_array_long_seq_test)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace myprotobuf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtobufCustomType_2eproto__INCLUDED
